server:
  port: 5000
#https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_PHP.rds.html
spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    #    generate-ddl: true
    show-sql: true

  flyway:
    baseline-on-migrate: true #uruchamia flywaya gdy schemat bazodanowy jest juz stworzony

  servlet:
    multipart:
      max-file-size: 3MB

cron:
  scheduler: '10 * * * * * *'
  path:  'target'

---
#profil local
server:
  port: 8099
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: root